# Generated by Django 4.2.7 on 2024-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
